### PR TITLE
docs: install the .who renderer package, how to emit HTML on the REPL

### LINKED ISSUE #6: Documentation, form rendering with :who
Hi,

I installed `cl-forms`, I tried to follow the documentation and to render a form.

https://mmontone.github.io/cl-forms/#Basics

```lisp
(let ((form (forms::find-form 'fields-form)))
  (forms:with-form-renderer :who
    (forms:render-form form)))
```

I first got a no-applicable method error:

```
; Evaluation aborted on #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {100F0E30F3}>.
```

I installed `cl-forms.who` (I saw it on Slime completion but not in the doc), now I get:

```
FORMS.WHO:*HTML* is unbound. Please bind it before rendering forms. See FORMS.WHO:*HTML* documentation.
```
OK, the doc says:

```
The stream where the form is rendered to, when using the who renderer.
Make sure to bind this before rendering your form.

Example:

(who:with-html-output (forms.who:*html*)
   (forms:render-form my-form))

Value: NIL
```

Trying:

```
(who:with-html-output (FORMS.WHO:*HTML*)
          (let ((form (forms::find-form 'fields-form)))
            (forms:with-form-renderer :who
              (forms:render-form form))))
```
=> nope, error: "The value of CL-FORMS.WHO:*HTML* is NIL, which is not of type STREAM."

What would an example that works at the REPL?

Then I could send a patch for the doc.

Thanks

### PR DESCRIPTION
**Pull request by vindarel**
fixes #6

That's one question resolved for the next ones.

### CODE REVIEW

**Comment by mmontone** [comment]
Nice. Thanks!

**Comment by mmontone** [comment]
Actually, I'm having to rewrite to correct file. The source of documentation is `cl-forms.source.texi` file. For next time ...

**Comment by vindarel** [comment]
Oops sorry. So you did it, it seems. Do you want to document the steps required to build the documentation? I see you committed changes to the html, pdf, .info, .texi, I could try to send a complete PR next time.

**Comment by mmontone** [comment]
To build the docs, update cl-forms.source.texi, then run make in docs directory.

**Pull request merged**
